#!/usr/bin/env python


def main():
    import sys

    gateway_host, gateway_port = sys.argv[1:3]
    gateway_addr = (gateway_host, int(gateway_port))

    from socket import AF_INET, SOCK_STREAM, socket

    skt = socket(AF_INET, SOCK_STREAM)

    skt.connect(gateway_addr)

    from common.comms.messages import HealthCheck

    healthcheck = HealthCheck().serialize()
    skt.sendall(healthcheck)

    HealthCheck.deserialize(skt.recv(len(healthcheck)))


if __name__ == "__main__":
    try:
        main()
        exit(0)
    except Exception:
        exit(1)
