"""
Generates docker-compose.clients.yaml based on NCLIENTS from test/cfg.py.
Run via: uv run gen_compose.py
"""

from cfg import NCLIENTS  # type: ignore[reportMissingImports]

_CLIENT_TEMPLATE = """\
  client_{n}:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_{n}
    depends_on:
      - gateway
    environment:
      - TRANSACTIONS_PATH=/datasets/transactions_{n}.csv
      - ACCOUNTS_PATH=/datasets/LI-Small_accounts.csv
      - RESPONSES_PATH=/responses/responses_{n}.csv
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=12345
      - NRESPONSES=5
      - BATCH_SIZE=500
    volumes:
      - ./datasets:/datasets
      - ./responses:/responses
"""

OUTPUT_PATH = "docker-compose.clients.yaml"


def main():
    clients = "".join(_CLIENT_TEMPLATE.format(n=n) for n in range(NCLIENTS))
    content = (
        f"# generated by gen_compose.py — do not edit manually\nservices:\n{clients}"
    )
    with open(OUTPUT_PATH, "w") as f:
        f.write(content)
    print(f"[gen_compose] wrote {OUTPUT_PATH} with {NCLIENTS} client(s)")


if __name__ == "__main__":
    main()
