"""
Generates docker-compose.clients.yaml based on NCLIENTS from test/cfg.py.
Run via: uv run gen_compose.py
"""

from cfg import NCLIENTS  # type: ignore[reportMissingImports]

_CLIENT_TEMPLATE = """\
  client_{n}:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_{n}
    depends_on:
      - gateway
    environment:
      - TRANSACTIONS_PATH=/datasets/transactions_{n}.csv
      - ACCOUNTS_PATH=/datasets/LI-Small_accounts.csv
      - RESPONSES_PATH=/responses/responses_{n}.csv
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=12345
      - NRESPONSES=5
      - BATCH_SIZE=500
    volumes:
      - ./datasets:/datasets
      - ./responses:/responses
"""

_REPORTER_DEPENDS_ENTRY = """\
      client_{n}:
        condition: service_completed_successfully
"""

_REPORTER_TEMPLATE = """\
  clients_reporter:
    image: alpine:3
    container_name: clients_reporter
    depends_on:
{depends}    command: >
      echo "all {nclients} clients exited with code 0"
"""

OUTPUT_PATH = "docker-compose.clients.yaml"


def main():
    clients = "".join(_CLIENT_TEMPLATE.format(n=n) for n in range(NCLIENTS))
    depends = "".join(_REPORTER_DEPENDS_ENTRY.format(n=n) for n in range(NCLIENTS))
    reporter = _REPORTER_TEMPLATE.format(depends=depends, nclients=NCLIENTS)
    content = (
        f"# generated by gen_compose.py — do not edit manually\nservices:\n{clients}{reporter}"
    )
    with open(OUTPUT_PATH, "w") as f:
        f.write(content)
    print(f"[gen_compose] wrote {OUTPUT_PATH} with {NCLIENTS} client(s)")


if __name__ == "__main__":
    main()
