CLIENT_TRANSACTIONS = "client_transactions"
CLIENT_ACCOUNTS = "client_accounts"

UC2_FILTERED_TRANSACTIONS = "uc2_filtered_transactions"
UC3_PERIOD_A_TRANSACTIONS = "uc3_transactons_period_A"
UC3_PERIOD_B_TRANSACTIONS = "uc3_transactons_period_B"
UC4_TRANSACTIONS = "uc4_filtered_transactions"
UC4_DEGREE_TRANSACTIONS = "uc4_degree_transactions"
UC5_TRANSACTIONS = "uc5_filtered_transactions"

UC1_JOIN = "uc1_join"
UC2_JOIN = "uc2_join"
UC3_JOIN = "uc3_join"
UC4_JOIN = "uc4_join"
UC5_JOIN = "uc5_join"
