# Supervisor
HEARTBEAT_INTERVAL = 1
HEARTBEAT_TIMEOUT = 3
REVIVE_INTERVAL = 0.5

# Chaos Monkey
CHAOS_INTERVAL = 10
CHAOS_KILLS_MIN = 1
CHAOS_KILLS_MAX = 5
CHAOS_START_DELAY = 5
CHAOS_EXCLUDE = "rabbitmq,supervisor,gateway,chaos"
