DEFAULT_FILTERS = 2

# UC2
UC2_MAX_AMOUNT_GROUP_BYS = 2
UC2_MAX_AMOUNT_AGGREGATES = 2
UC2_BANK_NAMES_GROUP_BYS = 2
UC2_BANK_NAMES_AGGREGATES = 2
UC2_MERGES = 2

# UC3
UC3_GROUP_BYS = 2
UC3_AGGREGATES = 2
UC3_MERGES = 2
UC3_FILTERS = 2

# UC4
UC4_COMPUTE_GRAPHS = 2
UC4_AGGREGATE_GRAPHS = 2
UC4_DEGREE_AGGREGATES = 2
UC4_PRUNES = 2
UC4_COUNT_PATHS = 2
UC4_PATHS_AGGREGATES = 2

# UC5
UC5_CONVERTERS = 2
UC5_AMOUNT_FILTERS = 2
UC5_COUNT_GROUP_BYS = 2

JOIN_PARTITION = [
    [1],
    [3],
    [2, 4, 5],
]
