"""
Generate docker-compose.clients.yaml from config.yaml.

Each container type has its own builder function so topology changes
(scaling a ring, adding a stage) are one-line edits.

Run via: uv run scripts/gen_compose.py
"""

import yaml

from config import accounts_path, nclients, responses_path

_OUTPUT = "docker-compose.clients.yaml"

_MOM = {"MOM_HOST": "rabbitmq", "MOM_PORT": 5672}
_RABBITMQ_HEALTHY = {"rabbitmq": {"condition": "service_healthy"}}


# ── primitives ────────────────────────────────────────────────────────────────


def gen_queue(name: str) -> str:
    """Identity — returns the queue name used as a connector between services."""
    return name


def _base_service(name: str, dockerfile: str, env: dict, depends_on=None, volumes: list | None = None) -> dict:
    svc: dict = {
        "build": {"context": "./src/", "dockerfile": f"{dockerfile}/Dockerfile"},
        "container_name": name,
        "depends_on": depends_on or _RABBITMQ_HEALTHY,
        "environment": [f"{k}={v}" for k, v in env.items()],
    }
    if volumes:
        svc["volumes"] = volumes
    return svc


# ── container builders ────────────────────────────────────────────────────────


def gen_filter_ring(name: str, rx: str, tx_map: dict, npeers: int, strategy: str | None = None) -> dict[str, dict]:
    """Build N filter replicas sharing a ring for coordinated EOF propagation."""
    ring_name = f"{name}_ring"
    services: dict[str, dict] = {}
    for i in range(npeers):
        svc_name = f"{name}_{i}"
        env = {**_MOM, "RX": rx, "IDX": i, "NPEERS": npeers, "RING_NAME": ring_name}
        if strategy:
            env["STRATEGY"] = strategy
        env.update(tx_map)
        services[svc_name] = _base_service(svc_name, "filter", env)
    return services


def gen_group_by_ring(name: str, strategy: str, rx: str, tx: str, npeers: int) -> dict[str, dict]:
    """Build N group-by replicas forming a ring."""
    ring_name = f"{name}_ring"
    services: dict[str, dict] = {}
    for i in range(npeers):
        svc_name = f"{name}_{i}"
        env = {**_MOM, "STRATEGY": strategy, "RX": rx, "TX": tx, "IDX": i, "NPEERS": npeers, "RING_NAME": ring_name}
        services[svc_name] = _base_service(svc_name, "group_by", env)
    return services


def gen_converter_ring(name: str, rx: str, tx: str, npeers: int) -> dict[str, dict]:
    """Build N converter replicas (UC5 currency conversion)."""
    ring_name = f"{name}_ring"
    services: dict[str, dict] = {}
    for i in range(npeers):
        svc_name = f"{name}_{i}"
        env = {**_MOM, "RX": rx, "TX": tx, "IDX": i, "NPEERS": npeers, "RING_NAME": ring_name}
        services[svc_name] = _base_service(svc_name, "converter", env)
    return services


def gen_aggregate(name: str, strategy: str, rx: str, tx: str, npeers_upstream: int | None = None) -> dict[str, dict]:
    """Build a single aggregate service."""
    env = {**_MOM, "STRATEGY": strategy, "RX": rx, "TX": tx}
    if npeers_upstream is not None:
        env["NPEERS_UPSTREAM"] = npeers_upstream
    return {name: _base_service(name, "aggregate", env)}


def gen_merge(name: str, strategy: str, left_rx: str, right_rx: str, tx: str) -> dict[str, dict]:
    """Build a merge service that joins two upstream queues."""
    env = {**_MOM, "LEFT_RX": left_rx, "RIGHT_RX": right_rx, "TX": tx, "STRATEGY": strategy}
    return {name: _base_service(name, "merge", env)}


def gen_client(n: int) -> dict[str, dict]:
    """Build a client service for client index n."""
    name = f"client_{n}"
    accs = f"/{accounts_path()}"
    resp = f"/{responses_path()}responses_{n}.csv"
    env = {
        "TRANSACTIONS_PATH": f"/datasets/transactions_{n}.csv",
        "ACCOUNTS_PATH": accs,
        "RESPONSES_PATH": resp,
        "GATEWAY_HOST": "gateway",
        "GATEWAY_PORT": 12345,
        "NRESPONSES": 5,
        "BATCH_SIZE": 500,
    }
    return {
        name: _base_service(
            name,
            "client",
            env,
            depends_on=["gateway"],
            volumes=["./datasets:/datasets", "./responses:/responses"],
        )
    }


# ── assembly ──────────────────────────────────────────────────────────────────


def main() -> None:
    nc = nclients()
    services: dict[str, dict] = {}
    for n in range(nc):
        services.update(gen_client(n))

    out = yaml.dump(
        {"services": services},
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )
    with open(_OUTPUT, "w") as f:
        f.write("# generated by scripts/gen_compose.py — do not edit manually\n")
        f.write(out)

    print(f"[gen_compose] wrote {_OUTPUT} with {nc} client(s)")


if __name__ == "__main__":
    main()
